<?php

namespace App\Http\Traits;

use App\Models\Contacts;
use App\Services\PdfGeneratorService;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use App\Http\Requests\BookingContact;
use Illuminate\Support\Facades\Storage;

trait BookingTraits
{
    public function getPaymentPdf()
    {
        $renderedView = view('pdf.bookingPayment', ['booking' => $this])->render();
        $pdfService = app(PdfGeneratorService::class);

        return $pdfService->generateFromHtml($renderedView, 'Legal');
    }

    public function getContractPdf(Contacts $contact = null): string
    {
        // Log contract generation attempt
        Log::info('Contract generation started', [
            'booking_id' => $this->id,
            'booking_name' => $this->name,
            'band_id' => $this->band->id,
            'band_name' => $this->band->name,
            'contact_id' => $contact?->id ?? $this->contacts->first()?->id,
        ]);

        // Validate band has required address fields
        $this->validateBandAddressData();

        $logoPath = str_replace('/images/', '', $this->band->logo);

        if (is_null($contact))
        {
            $contact = $this->contacts->first();
        }

        // Use Storage facade instead of direct file_get_contents
        $imageContents = Storage::disk('s3')->get($logoPath);
        $base64Image = base64_encode($imageContents);
        $mimeType = Storage::disk('s3')->mimeType($logoPath);
        $dataUri = "data:{$mimeType};base64,{$base64Image}";

        $renderedView = view('pdf.bookingContract', [
            'booking' => $this,
            'logoDataUri' => $dataUri,
            'signer' => $contact
        ])->render();

        $pdfService = app(PdfGeneratorService::class);

        $pdf = $pdfService->generateFromHtml($renderedView, 'Legal', true);

        // Log successful generation
        Log::info('Contract generated successfully', [
            'booking_id' => $this->id,
            'band_id' => $this->band->id,
            'pdf_size' => strlen($pdf),
        ]);

        return $pdf;
    }

    /**
     * Validate that the band has the required address data for contract generation
     *
     * @throws \InvalidArgumentException
     */
    protected function validateBandAddressData(): void
    {
        $requiredFields = [
            'name' => 'band name',
            'address' => 'street address',
            'city' => 'city',
            'state' => 'state',
            'zip' => 'zip code'
        ];

        $missingFields = [];

        foreach ($requiredFields as $field => $label) {
            if (empty($this->band->$field)) {
                $missingFields[] = $label;
            }
        }

        if (!empty($missingFields)) {
            $errorMessage = "Band '{$this->band->name}' is missing required fields for contract generation: " .
                implode(', ', $missingFields) .
                ". Please update the band's address information before generating a contract.";

            // Log validation failure
            Log::warning('Contract generation validation failed', [
                'booking_id' => $this->id,
                'band_id' => $this->band->id,
                'band_name' => $this->band->name,
                'missing_fields' => $missingFields,
            ]);

            throw new \InvalidArgumentException($errorMessage);
        }
    }

    public function storeContractPdf(string $contractPdf)
    {
        $contractPath = $this->band->site_name . '/contracts/' . $this->name . '_contract_' . time() . '.pdf';

        Storage::disk('s3')->put(
            $contractPath,
            $contractPdf,
            ['visibility' => 'public']
        );

        // Store just the path, not the full URL
        // The URL will be generated by the controller when needed
        $this->contract()->updateOrCreate(
            [], // No conditions, just find the first contract or create new
            [
                'asset_url' => '/' . ltrim($contractPath, '/'),
                'author_id' => auth()->id(),
                'status' => 'completed', // Mark as completed since manually uploaded contracts are already signed
            ]
        );
    }
}
