name: Laravel Docker Tests

on:
  push:
    branches: [master, staging, dev]
  pull_request:
    branches: [master, staging, dev]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker containers
        run: docker-compose up -d

      - name: Install dependencies
        run: docker-compose exec -T app composer install

      - name: Generate key
        run: docker-compose exec -T app php artisan key:generate

      - name: Run database migrations
        run: docker-compose exec -T app php artisan migrate

      - name: Run tests
        run: docker-compose exec -T app php artisan test

      - name: Stop Docker containers
        run: docker-compose down
