name: Laravel NPM Build

on:
  push:
    branches: [master, staging, dev]
  pull_request:
    branches: [master, staging, dev]

jobs:
  laravel-npm-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.7.0"

      - name: Install specific npm version
        run: npm install -g npm@10.8.2

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-assets
          path: public/build/**

      - name: Output Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: List build output
        run: ls -R public/build
