name: Laravel Tests

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: true
        type: string
      npm-version:
        description: 'NPM version'
        required: true
        type: string
      php-version:
        description: 'PHP version'
        required: true
        type: string
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql-test:
        image: mysql:8.1
        env:
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_DATABASE: "ttsband"
          MYSQL_USER: "tts"
          MYSQL_PASSWORD: "password"
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}

      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Update .env
        run: |
          echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env.testing

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install specific npm version
        run: npm install -g npm@${{ inputs.npm-version }}

      - name: Cache node_modules and composer dependencies
        uses: actions/cache@v4
        id: cache-node-and-composer
        with:
          path: |
            ~/.composer/cache
            **/vendor
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        if: steps.cache-node-and-composer.outputs.cache-hit != 'true'
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Install NPM dependencies
        if: steps.cache-node-and-composer.outputs.cache-hit != 'true'
        run: npm ci
      
      - name: Build assets
        run: npm run build

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Cache wkhtmltopdf .deb file
        uses: actions/cache@v4
        id: cache-wkhtmltopdf
        with:
          path: ~/wkhtmltopdf.deb
          key: ${{ runner.os }}-wkhtmltopdf-0.12.6.1-2
      
      - name: Install wkhtmltopdf
        run: |
          if [ ! -f ~/wkhtmltopdf.deb ]; then
            echo "Downloading wkhtmltopdf .deb file"
            wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_amd64.deb -O ~/wkhtmltopdf.deb
          else
            echo "Using cached wkhtmltopdf .deb file"
          fi
      
          echo "Adding Debian repository for libjpeg62-turbo"
          echo "deb http://security.debian.org/debian-security bullseye-security main" | sudo tee /etc/apt/sources.list.d/debian-security.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A
      
          echo "Updating package lists"
          sudo apt-get update
      
          echo "Installing libjpeg62-turbo"
          sudo apt-get install -y libjpeg62-turbo
      
          echo "Installing wkhtmltopdf"
          sudo apt-get install -y ~/wkhtmltopdf.deb
      
          echo "Verifying installation"
          wkhtmltopdf --version
      

      - name: Execute tests via Artisan
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1 
        run: php artisan test
