# .github/workflows/deploy.yml
name: Deploy

on:
  pull_request:
    branches: 
      - master
      - staging
      - dev
    types: [closed]
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/forgeDeploy.yml
    with:
      environment: ${{ github.base_ref == 'master' && 'production' || 'staging' }}
    secrets: inherit