# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [master, staging, dev]

jobs:
  deploy:
    uses: ./.github/workflows/forgeDeploy.yml
    with:
      environment: ${{ github.base_ref == 'master' && 'production' || 'staging' }}
    secrets: inherit