name: Deploy to Forge

on:
  pull_request:
    branches: 
      - master
      - staging
      - dev
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref == 'master' && 'production' || 'staging' }}
    steps:
    - name: Trigger Forge Deployment
      env:
        FORGE_DEPLOYMENT_WEBHOOK: ${{ secrets.FORGE_DEPLOYMENT_WEBHOOK }}
      run: |
        curl -X POST ${{ secrets.FORGE_DEPLOYMENT_WEBHOOK }}