name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize]
    branches: [master, staging, dev]
jobs:
  frontend:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/frontend.yml
    with:
      node-version: ${{ vars.NODE_VERSION }}
      npm-version: ${{ vars.NPM_VERSION }}
      php-version: ${{ vars.PHP_VERSION }}

  backend:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/backendTests.yml
    with:
      node-version: ${{ vars.NODE_VERSION }}
      npm-version: ${{ vars.NPM_VERSION }}
      php-version: ${{ vars.PHP_VERSION }}

  auto-merge:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - name: Merge pull request
        run: |
          gh pr merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  