name: CI/CD Pipeline

on:
    push:
        branches: [master, staging, dev]
    pull_request:
        branches: [master, staging, dev]
env:
    NODE_VERSION: "22.7.0"
    NPM_VERSION: "10.8.2"
    PHP_VERSION: "8.1"
jobs:
    frontend:
        uses: ./.github/workflows/frontend.yml
        with:
            node-version: $NODE_VERSION
            npm-version: $NPM_VERSION
            php-version: $PHP_VERSION
    backend:
        uses: ./.github/workflows/backendTests.yml
        with:
            node-version: $NODE_VERSION
            npm-version: $NPM_VERSION
            php-version: $PHP_VERSION
    deploy:
        needs: [frontend, backend]
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging'
        uses: ./.github/workflows/forgeDeploy.yml
        with:
            environment:  ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
        secrets: inherit

  