name: CI/CD Pipeline

on:
    push:
        branches: [master, staging, dev]
    pull_request:
        branches: [master, staging, dev]
jobs:
    frontend:
        uses: ./.github/workflows/frontend.yml
        with:
            node-version: ${{ vars.NODE_VERSION }}
            npm-version: ${{ vars.NPM_VERSION }}
            php-version: ${{ vars.PHP_VERSION }}
    backend:
        uses: ./.github/workflows/backendTests.yml
        with:
            node-version: ${{ vars.NODE_VERSION }}
            npm-version: ${{ vars.NPM_VERSION }}
            php-version: ${{ vars.PHP_VERSION }}
    deploy:
        needs: [frontend, backend]
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging'
        uses: ./.github/workflows/forgeDeploy.yml
        with:
            environment:  ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
        secrets: inherit

  